apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: {{ .Values.app.name }}
  type: LoadBalancer
